package storage
package storage

































































}	return &key, nil	}		return nil, err	if err != nil {	err := row.Scan(&key.ID, &key.ProjectID, &key.KeyHash, &key.Name, &key.ExpiresAt)	var key models.APIKey	row := s.pool.QueryRow(ctx, query, hash)	query := `SELECT id, project_id, key_hash, name, expires_at FROM api_keys WHERE key_hash = $1`func (s *PostgresStore) GetAPIKeyByHash(ctx context.Context, hash string) (*models.APIKey, error) {}	return &event, nil	}		return nil, err	if err != nil {		&event.Timestamp, &event.Metadata, &event.ReceivedAt, &event.IPAddress, &event.UserAgent)	err := row.Scan(&event.ID, &event.ProjectID, &event.EventName, &event.UserID,	var event models.Event	row := s.pool.QueryRow(ctx, query, id)	query := `SELECT id, project_id, event_name, user_id, timestamp, metadata, received_at, ip_address, user_agent FROM events WHERE id = $1`func (s *PostgresStore) GetEventByID(ctx context.Context, id string) (*models.Event, error) {}	return err		event.IPAddress, event.UserAgent, event.IdempotencyKey)		event.Timestamp, event.Metadata, event.ReceivedAt,		event.ID, event.ProjectID, event.EventName, event.UserID,	_, err := s.pool.Exec(ctx, query,	`		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)		INSERT INTO events (id, project_id, event_name, user_id, timestamp, metadata, received_at, ip_address, user_agent, idempotency_key)	query := `func (s *PostgresStore) InsertEvent(ctx context.Context, event *models.Event) error {}	s.pool.Close()func (s *PostgresStore) Close() {}	return &PostgresStore{pool: pool}, nil	}		return nil, err	if err != nil {	pool, err := pgxpool.New(context.Background(), url)func NewPostgres(url string) (*PostgresStore, error) {}	pool *pgxpool.Pooltype PostgresStore struct {}	GetAPIKeyByHash(ctx context.Context, hash string) (*models.APIKey, error)	GetEventByID(ctx context.Context, id string) (*models.Event, error)	InsertEvent(ctx context.Context, event *models.Event) errortype EventStore interface {)	"github.com/jackc/pgx/v5/pgxpool"	"realtime-events/internal/models"	"context"import (